database:
  host: 'host.docker.internal'
  port: 5432
  name: 'apihub_backend'
  username: 'apihub_backend_user'
  password: 'apihub_backend_password'
security:
  # required to enable local users
  productionMode: false
  jwt:
    # <put_your_key_here - ssh private key base64 encoded>
    privateKey: ${JWT_PRIVATE_KEY}
  apihubExternalUrl: 'http://host.docker.internal:8081'
  allowedHostsForProxy:
    - 'host.docker.internal'
    - 'localhost'
zeroDayConfiguration:
  # <access_token, example: 1RnECckUUB>
  accessToken: ${APIHUB_ACCESS_TOKEN}
  # <admin_login, example: apihub>
  adminEmail: ${APIHUB_ADMIN_EMAIL}
  # <admin_password, example: password>
  adminPassword: ${APIHUB_ADMIN_PASSWORD}