apiVersion: v1
kind: Service
metadata:
  name: pg-common
  labels:
    app: pg-common
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5432
  selector:
    app: pg-common