# Section with global APIHUB configuration
qubershipApihub:

  # Optional; APIHUB release version to be shown in UI; If not set, default value: unknown; Example: 37653
  version: ''

  # Optional; Set log level on init to specified value. Values: Info, Warn, Error, etc; If not set, default value: INFO; Example: DEBUG
  logLevel: ''

  # Mandatory; Default system access token (any string). The token will be provisioned automatically during startup; If not set, default value: ""; Example: access-token-12345
  accessToken: ''

  # Mandatory; Factual APIHUB server URL in your environment.; If not set, default value: ""; Example: https://apihub.example.com
  apihubUrl: ''

# Section with APIHUB Backend configuration
qubershipApihubBackend:
  image:
    repository: 'ghcr.io/netcracker/qubership-apihub-backend'
    tag: 'latest'
  replicas: 1

  # Section with resource limits
  # Mandatory
  # Below are the default values which are good enough for quick start, sandbox and over non production cases
  # For production usage increase CPU to 3 and memory to 3Gi
  resource:
    cpu:
      request: "100m"
      limit: "1"
    memory:
     limit: "512Mi"

  # Section with monitoring configuration for APIHUB
  # APIHUB backend is using Prometheus for monitoring and Grafana for visualization
  monitoring:
    # Optional; Enables creation of Service Monitor. If not set, default value: FALSE; Example: TRUE
    enabled: ''

  # Section with business and technical parameters for APIHUB.
  env:

    # Optional; Enables production mode - login under local apihub users is prohibited in this mode. In this mode only SAML auth is possible, so SAML integration related deploy parameters are mandatory in this case; If not set, default value: FALSE; Example: TRUE
    productionMode: 'true'  # set to false at your own risk

    # Section with PostgreSQL database connection parameters
    database:
      # Mandatory; PostgreSQL database host ; If not set, default value: localhost; Example: postgres.example.com
      dbHost: ''
      # Mandatory; PostgreSQL database port; If not set, default value: 5432; Example: 5432
      dbPort: ''
      # Mandatory; Logical database in PostgreSQL cluster for APIHUB. Manual pre-creation required; If not set, default value: apihub; Example: apihub_backend_prod_db
      dbName: ''
      # Mandatory; User for APIHUB_POSTGRESQL_DB_NAME database; If not set, default value: apihub; Example: apihub_backend_prod_admin
      dbUsername: ''
      # Mandatory; Password for APIHUB_POSTGRESQL_USERNAME user.; If not set, default value: apihub; Example: apihub_backend_prod_password
      dbPassword: ''

    # Section with parameters for configuring JWT tokens issued by APIHUB
    jwt:
      # Mandatory; Self generated private PKCS#8 private key, base64 encoded. Used for siging of JWT tokens issued by APIHUB, must be unique fore each APIHUB instance; If not set, default value: ""; Example: LS0tLS1CRUdJTiBQUklWQV...
      privateKey: ''
      # Optional; Duration in seconds for access tokens issued by APIHUB; If not set, default value: 3600; Example: 3600
      accessTokenDurationSec: ''
      # Optional; Duration in seconds for refresh tokens issued by APIHUB; If not set, default value: 43200; Example: 43200
      refreshTokenDurationSec: ''

    # Optional; Default local admin user login. If set - this admin user will be created automatically.; If not set, default value: ""; Example: admin@example.com
    adminEmail: ''
    # Optional; Default local admin user password; If not set, default value: ""; Example: admin-password
    adminPassword: ''

    # Section with authentication configuration
    auth:
      # Optional; Enables automatic login with the configured identity provider instead of showing the APIHUB login page; If not set, default value: FALSE; Example: TRUE
      autoLogin: 'false'
      # Optional; To be deleted, WA for smooth upgrade of exisiting deployments; If not set, default value: TRUE; Example: FALSE
      legacySaml: 'false'
      # External identity providers configuration. SAML or OIDC integration is mandatory for production mode.
      externalIdentityProviders:
        # Section with SAML integration parameters. SAML integration is used for authentication of APIHUB users. SAML integration is mandatory for production mode.
        saml:
          # Optional; Display name for external SAML identity provider; If not set, default value: ""; Example: External Identity Provider
          displayName: ''
          # Optional; SVG image for external SAML identity provider logo; If not set, default value: ""; Example: <svg fill="#000000" width="800px"...
          imageSvg: ''
          # Optional; SAML metadata URL. Required for SAML configuration; If not set, default value: ""; Example: https://idp.example.com/FederationMetadata/2007-06/FederationMetadata.xml
          metadataUrl: ''
          # Optional; SAML server certificate, base64 encoded. Required for SAML configuration; If not set, default value: ""; Example: LS0tLS1CRUdJTi...
          certificate: ''
          # Optional; SAML server private key, base64 encoded. Required for SAML configuration; If not set, default value: ""; Example: LS0tLS1CRUdJTi...
          privateKey: ''
        # Section with OIDC integration parameters. OIDC integration is used for authentication of APIHUB users.
        oidc:
          # Optional; Display name for external OIDC identity provider; If not set, default value: ""; Example: External Identity Provider
          displayName: ''
          # Optional; SVG image for external OIDC identity provider logo; If not set, default value: ""; Example: <svg fill="#000000" width="800px"...
          imageSvg: ''
          # Optional; OIDC identity provider URL. Required for OIDC configuration; If not set, default value: ""; Example: https://idp.example.com/realms/apihub
          providerUrl: ''
          # Optional; OIDC client ID. Required for OIDC configuration; If not set, default value: ""; Example: apihub
          clientId: ''
          # Optional; OIDC client secret. Required for OIDC configuration; If not set, default value: ""; Example: l5cKFvwDRSnhBErE9LUGeBk0dqqFB7No
          clientSecret: ''

    # Section with various parameters related to APIHUB business logic
    businessParameters:
      # Optional; Links to be shown under (i) button in UI; If not set, default value: ""; Example: 
      externalLinks: ''
      # Optional; Default workspace ID for Agent UI; If not set, default value: ""; Example: QS
      defaultWorkspaceId: ''
      # Optional; Regex pattern for releases names validation.; If not set, default value: ^[0-9]{4}[.]{1}[1-4]{1}$; Example: ^2023\.1$
      releaseVersionPattern: '.*'
      # Optional; Limit for uploaded package size in order to avoid OOM; If not set, default value: 50; Example: 50
      publishArchiveSizeLimitMb: '50'
      # Optional; Limit for uploaded file (inside package) size in order to avoid OOM; If not set, default value: 15; Example: 20
      publishFileSizeLimitMb: '15'
      # Optional; If set - footer with this text is shown for all APIHUB users in APIHUB UI. Designed for maintenance windows notifications.; If not set, default value: ""; Example: Maintenance scheduled on 2023-10-15
      systemNotification: ''
      # Optional; Set to true to enable apihub playground work without authtorization. Dangerous. Not recommended; If not set, default value: FALSE; Example: FALSE
      insecureProxy: 'FALSE'
      # Optional; Allowed list of hosts that are accepted for proxy(playground) requests.; If not set, default value: ""; Example: *.example.com
      allowedHosts: ''

    # Section with various parameters related to APIHUB technical behavior 
    technicalParameters:
      # Optional; Allows to set extra allowed origin to CORS header. Used for FE debugging. Should be empty on prod evs.; If not set, default value: ""; Example: https://localhost:5137
      originAllowed: ''
      # Optional; Allows to specify custom paths for extension (plug-in) backend services; If not set, default value: ""; Example: 
      customPathPrefixes: ''

    # Section with LDAP integration parameters. LDAP integration is used for User syncronization. Makes sense only if SAML integration enabled.
    ldap:
      # Optional; LDAP server URL. Required for SAML integration for syncing users information; If not set, default value: ""; Example: ldap://ldap.example.com:389
      server: ''
      # Optional; LDAP User used for connecting to LDAP server; If not set, default value: ""; Example: x_apihub
      user: ''
      # Optional; Password for LDAP User; If not set, default value: ""; Example: x_apihub_password
      password: ''
      # Optional; Base DN to search users in; If not set, default value: ""; Example: organization
      baseDN: ''
      # Optional; Organization unit to search users in; If not set, default value: ""; Example: example
      organizationUnit: ''
      # Optional; Search base to search users in; If not set, default value: ""; Example: com
      searchBase: ''

    # Section with S3 storage integration parameters.
    storageServer:
      # Optional; Set to true to enable S3 integration. S3 is used for store temporary relatively large files.; If not set, default value: FALSE; Example: TRUE
      active: 'FALSE'
      # Optional; S3 endpoint for client connection; If not set, default value: ""; Example: s3.example.com
      url: ''
      # Optional; Access Key ID from S3 storage; If not set, default value: ""; Example: s3-access-key
      username: ''
      # Optional; Secret key for S3 storage access; If not set, default value: ""; Example: s3-secret-key
      password: ''
      # Optional; Certificate for accessing S3 storage; If not set, default value: ""; Example: LS0tLS1CRUdJTiBQUklWQV...
      crt: ''
      # Optional; Bucket name in S3 storage; If not set, default value: ""; Example: apihub-bucket
      bucketTame: ''
      # Optional; Set to true to store only build results (less data amout) in S3 storage; If not set, default value: FALSE; Example: TRUE
      storeOnlyBuildResult: ''
    
    # Section with revisions cleanup job configuration
    revisionsCleanup:
      # Optional; If set to true, the revisions cleanup job will delete the last revision of the version. Otherwise, such revisions are skipped; If not set, default value: false; Example: true
      deleteLastRevision: 'false'
      # Optional; If set to true, the revisions cleanup job will delete revisions with a 'release' status. Otherwise, such revisions are skipped; If not set, default value: false; Example: true
      deleteReleaseRevisions: 'false'
      # Optional; Number of days to keep revisions before cleanup; If not set, default value: 365; Example: 180
      ttlDays: '365'

    # Parameters for APIHUB Editor feature. Deprecated. Will be removed in future releases.
    editor:
      gitlabUrl: ''
      clientId: ''
      clientSecret: ''

# Section with APIHUB Build Task Consumer configuration
qubershipApihubBuildTaskConsumer:
  image:
    repository: 'ghcr.io/netcracker/qubership-apihub-build-task-consumer'
    tag: 'latest'
  replicas: 1

  # Section with resource limits
  # Mandatory
  # Below are the default values which are good enough for any cases including production
  # For production usage increase replicas to 3 or 6
  resource:
    cpu:
      request: "100m"
      limit: "1.25"
    memory:
     limit: "4200Mi"
     request: "750Mi"
  env:
    operationsBuildBatch: "16" # most likely never change this value

# Section with APIHUB UI configuration
qubershipApihubUi:
  image:
    repository: 'ghcr.io/netcracker/qubership-apihub-ui'
    tag: 'latest'
  replicas: 1

  # Section with resource limits
  # Mandatory
  # Below are the default values which are good enough for any cases including production
  resource:
    cpu:
      request: "30m"
      limit: "1"
    memory:
     limit: "256Mi"
     request: "64Mi"
  env:
    apihubBackendAddress: 'qubership-apihub-backend:8080' # k8s local address of apihub backend service. Do not change it unless you know what you are doing
    apihubNcServiceAddress: 'qubership-apihub-backend:8080' # k8s local address of apihub custom service. Do not change it unless you know what you are doing

  # Flag to enable/disable http UI ingress creation
  ingress:
    enabled: false

  # Flag to enable/disable https UI ingress creation
  # https Ingress URL is used in APIHUB_URL ENV VAR on qubership-apihub-backend, so disabling its creation will make APIHUB deployment unable to work
  tlsIngress:
    enabled: true
    tlsSecret:
      # Certificate used for TLS termination in https ingress
      certificate: ''
      # Private key for certificate above
      certificateKey: ''
