{
 "title": "APIHUB Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(apihub_http_requests_total,cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(apihub_http_requests_total{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(apihub_http_requests_total{cluster=\"$cluster\",namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Build", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Max build time for the day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "apihub_max_build_time{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG build time for the day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "apihub_avg_build_time{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Builds in none status for the day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "apihub_build_none_queue_size{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of build retries for the day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "apihub_build_retries_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Builds in running status for the day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "apihub_build_running_queue_size{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed builds for the day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "apihub_failed_build_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WS Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "WS branch edit sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "apihub_ws_branch_edit_session_count{cluster=\"$cluster\",namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WS file edit sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "apihub_ws_file_edit_session_count{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by(pod) (increase(apihub_http_requests_total{pod=~\"$pod\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per minute with response code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum by(pod, code, path, method) (increase(apihub_http_requests_total{pod=~\"$pod\", cluster=\"$cluster\", namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(apihub_http_request_duration_seconds_historgram_sum{pod=~\"${pod}\", cluster=\"$cluster\",namespace=\"$namespace\"}[1m]) / rate(apihub_http_request_duration_seconds_historgram_count{pod=~\"${pod}\", cluster=\"$cluster\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time by 0.99 quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apihub_http_request_duration_seconds_historgram_bucket{cluster=\"$cluster\",namespace=\"$namespace\", pod=\"$pod\"}[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(apihub_http_requests_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",code=~\"4.+|5.+\"}[1m])) / sum(increase(apihub_http_requests_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\"}[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(apihub_http_requests_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=\"$pod\",code =~\"4.+|5.+\"})[1m]) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "label_replace((sum by(instance)(rate(process_cpu_seconds_total{job=\"kube-state-metrics\", cluster=\"$cluster\"}[5m]))\n), \"host_ip\", \"$1\", \"instance\", \"([^:]+)(:(.*))*\"\n)\n* on(host_ip) group_left(pod, node) (kube_pod_info{pod=~\"api-hub-dev-*\", cluster=\"$cluster\", host_network=\"true\"})\nor on (instance)\nlabel_replace((sum by(instance)(rate(process_cpu_seconds_total{job=\"kube-state-metrics\", cluster=\"$cluster\"}[5m]))\n), \"pod\", \"$1\", \"instance\", \"(.*)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"$namespace\", pod=~\"$pod\", container!~\"POD|\", image!=\"\"}) by (pod, container)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Goroutines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\",pod=~\"$pod\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}