apiVersion: v1
stringData:
  saml_crt: '{{ .Values.qubershipApihubBackend.env.auth.externalIdentityProviders.saml.certificate }}'
  saml_key: '{{ .Values.qubershipApihubBackend.env.auth.externalIdentityProviders.saml.privateKey }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-saml-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque