apiVersion: v1
stringData:
  ldap_user: '{{ .Values.qubershipApihubBackend.env.ldap.user }}'
  ldap_user_password: '{{ .Values.qubershipApihubBackend.env.ldap.password }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-ldap-user-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque
