apiVersion: v1
stringData:
  storage_server_access_key_id: '{{ .Values.qubershipApihubBackend.env.storageServer.username }}'
  storage_server_secret_access_key: '{{ .Values.qubershipApihubBackend.env.storageServer.password }}'
  storage_server_crt: '{{ .Values.qubershipApihubBackend.env.storageServer.crt }}'
  storage_server_endpoint: '{{ .Values.qubershipApihubBackend.env.storageServer.url }}'
  storage_server_bucket_name: '{{ .Values.qubershipApihubBackend.env.storageServer.bucketName }}'
  storage_server_active: '{{ .Values.qubershipApihubBackend.env.storageServer.active }}'
  storage_server_store_only_build_result: '{{ .Values.qubershipApihubBackend.env.storageServer.storeOnlyBuildResult }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-storage-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque