---
apiVersion: v1
kind: Secret
metadata:
    name: 'qubership-apihub-build-task-consumer-secret'
    namespace: '{{ .Release.Namespace }}'
    annotations:
        kubernetes.io/service-account.name: 'qubership-apihub-build-task-consumer'
    labels:
        app.kubernetes.io/part-of: qubership-apihub
        app.kubernetes.io/managed-by: helm
type: kubernetes.io/service-account-token

