apiVersion: v1
stringData:
  client_id: '{{ .Values.qubershipApihubBackend.env.editor.clientId }}'
  client_secret: '{{ .Values.qubershipApihubBackend.env.editor.clientSecret }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-gitlab-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
      app.kubernetes.io/part-of: qubership-apihub
      app.kubernetes.io/managed-by: helm
type: Opaque