---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: 'qubership-api-linter-service'
    namespace: '{{ .Release.Namespace }}'
    labels:
        app.kubernetes.io/part-of: qubership-apihub
        app.kubernetes.io/managed-by: helm

