apiVersion: v1
stringData:
  oidc_client_id: '{{ .Values.qubershipApihubBackend.env.auth.externalIdentityProviders.oidc.clientId }}'
  oidc_client_secret: '{{ .Values.qubershipApihubBackend.env.auth.externalIdentityProviders.oidc.clientSecret }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-oidc-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque