{{- if .Values.qubershipApihubUi.tlsIngress.enabled }}
apiVersion: v1
data:
  tls.crt: '{{ .Values.qubershipApihubUi.tlsIngress.tlsSecret.certificate }}'
  tls.key: '{{ .Values.qubershipApihubUi.tlsIngress.tlsSecret.certificateKey }}'
kind: Secret
metadata:
  name: 'qubership-apihub-ui-tls'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque
{{- end }}