apiVersion: v1
stringData:
  apihub_admin_email: '{{ .Values.qubershipApihubBackend.env.adminEmail }}'
  apihub_admin_password: '{{ .Values.qubershipApihubBackend.env.adminPassword }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-zero-day-admin-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque