---
apiVersion: v1
data:
  config.yaml: {{ .Values.qubershipApihub | b64enc }}
kind: Secret
metadata:
  name: qubership-apihub--config-secret
  labels:
      app.kubernetes.io/part-of: qubership-apihub
      app.kubernetes.io/managed-by: helm
type: Opaque