apiVersion: v1
stringData:
  apihub_postgresql_username: '{{ .Values.qubershipApihubBackend.env.database.dbUsername }}'
  apihub_postgresql_password: '{{ .Values.qubershipApihubBackend.env.database.dbPassword }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-db-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque

