apiVersion: v1
stringData:
  jwt_private_key: '{{ .Values.qubershipApihubBackend.env.jwt.privateKey }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-jwt-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque