apiVersion: v1
stringData:
  token: '{{ .Values.qubershipApihub.accessToken }}'
kind: Secret
metadata:
  name: 'qubership-apihub-backend-access-token-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
      app.kubernetes.io/part-of: qubership-apihub
      app.kubernetes.io/managed-by: helm
type: Opaque