apiVersion: v1
stringData:
  access_token: '{{ .Values.qubershipApihubBuildTaskConsumer.env.accessToken }}'
kind: Secret
metadata:
  name: 'qubership-apihub-build-task-consumer-api-key-secret'
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/part-of: qubership-apihub
    app.kubernetes.io/managed-by: helm
type: Opaque

